### ISSUE TITLE
Can we release this project on PyPI?

### ISSUE THREAD

**Issue by palewire** [biglocalnews/bln-etl#9]
It seems like a good thing to do long term, and might be required by tickets [like this](https://github.com/biglocalnews/warn-scraper/issues/305).

**Comment by zstumgoren** [comment]
Let's discuss this as a team at next weekly. I had originally created this as a quick-and-dirty wrapper for some tooling I needed to begin standardizing some ETL jobs that feed the BLN platform. You've probably noticed it's a hodgepodge in terms of functionality (wraps/fixes parts of the official SDK; adds some random tooling to create compressed files, etc.).

Anyhow, I'm not opposed to the idea of putting on PyPI, but would be good to include @esagara in the discussion

**Comment by zstumgoren** [comment]
@palewire I should add that all the other issues you've added for tidying up are very welcome!
